# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: lissner-site-api # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

# Use serverless-webpack plugin to transpile ES6/7
plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-west-2

# you can add statements to the Lambda function's IAM Role here
iamRoleStatements:
  - Effect: "Allow"
    Action:
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
    Resource: "arn:aws:dynamodb:us-west-2:*:*"

functions:
  get-recipes:
    handler: recipes.get
    events:
      - http:
          path: recipes
          method: get
          cors: true
          authorizer: aws_iam
  create-recipe:
    handler: recipes.create
    events:
      - http:
          path: recipes
          method: post
          cors: true
          authorizer: aws_iam
  update-recipes:
    handler: recipes.update
    events:
      - http:
          path: recipes
          method: put
          cors: true
          authorizer: aws_iam
  get-tags:
    handler: tags.get
    events:
      - http:
          path: tags
          method: get
          cors: true
          authorizer: aws_iam