# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: lissner-site-api # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

# Use serverless-webpack plugin to transpile ES6/7
plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-west-2

# you can add statements to the Lambda function's IAM Role here
# if you get an access denied after deploying
# add the below to the role "lissner-site-api-prod-us-west-2-lambdaRole"
# as part of the "prod-lissner-site-api-lambda" policy
# {
#   "Effect": "Allow",
#   "Action": [
#       "dynamodb:*"
#   ],
#   "Resource": [
#       "arn:aws:dynamodb:us-west-2:*:*"
#   ]
# },
iamRoleStatements:
  - Effect: "Allow"
    Action:
      - dynamodb:*
    Resource: "arn:aws:dynamodb:us-west-2:*:*"

functions:
  get-users:
    handler: users.get
    events:
      - http:
          path: users
          method: get
          cors: true
          authorizer: aws_iam
  create-user:
    handler: users.create
    events:
      - http:
          path: users
          method: post
          cors: true
          authorizer: aws_iam
  update-user:
    handler: users.update
    events:
      - http:
          path: users
          method: put
          cors: true
          authorizer: aws_iam
  get-recipes:
    handler: recipes.get
    events:
      - http:
          path: recipes
          method: get
          cors: true
          authorizer: aws_iam
  create-recipe:
    handler: recipes.create
    events:
      - http:
          path: recipes
          method: post
          cors: true
          authorizer: aws_iam
  update-recipe:
    handler: recipes.update
    events:
      - http:
          path: recipes
          method: put
          cors: true
          authorizer: aws_iam
  get-tags:
    handler: tags.get
    events:
      - http:
          path: tags
          method: get
          cors: true
          authorizer: aws_iam
  get-quotes:
    handler: quotes.get
    events:
      - http:
          path: quotes
          method: get
          cors: true
          authorizer: aws_iam